name: Build and Publish Firefox Extension

on:
  push:
    tags:
      - '*' # Trigger on version tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-package-lock

      - name: Build extension
        run: npm run build:firefox

      - name: Create source zip
        run: |
          zip -r source.zip \
            webpack.config.js \
            tsconfig.json \
            build.sh \
            package.json \
            .babelrc \
            README.md \
            source \
            views

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Sign and publish extension
        run: |
          web-ext sign \
            --source-dir ./dist \
            --artifacts-dir ./web-ext-artifacts \
            --api-key ${{ secrets.FIREFOX_API_KEY }} \
            --api-secret ${{ secrets.FIREFOX_API_SECRET }} \
            --channel listed \
            --upload-source-code source.zip